receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
      http:
        endpoint: 0.0.0.0:14318
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    remote_write_queue:
      enabled: false
    retry_on_failure:
      enabled: false
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true


extensions:
  health_check:
  pprof:
  zpages:

service:
  telemetry:
    logs:
      level: "DEBUG"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/loki]
