
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy 
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
- name: Loki
  type: loki
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  access: proxy
  jsonData:
    derivedFields:
    - datasourceUid: "Tempo"
      matcherRegex: "TraceId"
      matcherType: "label"
      name: "TraceId"
      url: "$${__value.raw}"
      urlDisplayLabel: "View Trace"
    - matcherRegex: service_name
      matcherType: label
      name: Host
      url: http://localhost:3000/d/cadvisor/cadvisor?var-container=apps-$${__value.raw}-1
      urlDisplayLabels: View Host Metrics
- name: Tempo
  type: tempo
  access: proxy 
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    nodeGraph:
      enabled: true
    serviceMap:
      datasourceUid: Prometheus
    tracesToLogsV2:
      customQuery: true
      datasourceUid: Loki
      filterBySpanID: false
      filterByTraceID: false
      query: '{$$__tags} | TraceId="$${__span.traceId}"'
      spanEndTimeShift: 15m
      spanStartTimeShift: -15m
      tags:
      - key: service.name
        value: service_name
    tracesToMetrics:
      datasourceUid: Prometheus
      queries:
      - name: Http Requests Metrics
        query: sum by (code) (irate(http_requests_total{$$__tags}[1m]))
      spanEndTimeShift: 15m
      spanStartTimeShift: -15m
      tags:
      - key: service.name
        value: job
