services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
    - --config=/conf/config.yaml
    volumes:
    - ./otel/config.yaml:/conf/config.yaml
    ports:
      - "14317:14317"  # otlp grpc
      - "14318:14318"  # otlp http
    networks:
    - o11y

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    image: grafana/grafana:latest
    volumes:
    - ./grafana/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
    - "3000:3000"
    networks:
    - o11y

  prometheus:
    image: prom/prometheus:latest
    command:
    - --config.file=/etc/prometheus.yaml
    - --web.enable-remote-write-receiver
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
    networks:
    - o11y

  tempo:
    image: grafana/tempo:latest
    command:
    - -config.file=/etc/tempo.yaml
    volumes:
    - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
    networks:
    - o11y

  loki:
    image: grafana/loki:latest
    ports:
    - "3100:3100"
    #command: -config.file=/etc/loki/local-config.yaml
    networks:
    - o11y

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
    - "8080:8080"
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:ro"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    - "/dev/disk/:/dev/disk:ro"
    networks:
    - o11y

networks:
  o11y:
