services:
  postgres:
    image: postgres:14-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=S3cret
    - POSTGRES_USER=app3
    - POSTGRES_DB=library
    networks:
    - o11y
networks:
  o11y:
